# ===========================================
# dnsmasq — VPN DNS server
# ===========================================

# Faqat tun0 va lo da tinglaydi
interface=tun0
interface=lo
bind-interfaces

# Port
port=53

# Upstream DNS (Google + Cloudflare)
server=8.8.8.8
server=8.8.4.4
server=1.1.1.1

# Cache
cache-size=1000
neg-ttl=60

# Domain
domain=test.uz
local=/test.uz/

# VPN subnet uchun DHCP emas, faqat DNS
no-dhcp-interface=tun0

# Log
log-queries
log-facility=/var/log/dnsmasq.log

# Hosts fayl
addn-hosts=/etc/dnsmasq.hosts

# DNS rebind himoya
stop-dns-rebind
rebind-localhost-ok
